### ISSUE TITLE
Maximum complexity config

### ISSUE THREAD

**Issue by kurtjerome** [Youshido/GraphQLBundle#15]
How can we set the Processor's maximum complexity?
Is there an undocumented config we can set to do this?

Youshido/GraphQL#22

**Comment by portey** [comment]
Hi, @kurtjerome 

You can require this bundle in version "dev-master" in your `composer.json` file and then configure it in `config.yml` like in example below:

``` yaml
graph_ql:
    schema_class: "AppBundle\\GraphQL\\Schema"
    max_complexity: 4
```
